card_image: https://raw.githubusercontent.com/memextech/ios-template/main/assets/card_image.png
created_at: 2025-03-20 18:50:59.256000
creator_id: your name
deployment:
  last_deployed: null
  type: github
  url: https://github.com/memextech/ios-template
description: A template for iOS app development using Xcode and Swift
domain: Mobile Development
features:
- Swift programming
- iOS UI development
- Xcode project management
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/memextech/ios-template
hero_image: https://raw.githubusercontent.com/memextech/ios-template/main/assets/hero_image.png
icon: DeviceMobile
is_published: false
pills:
- icon: DeviceMobile
  label: Create iOS App
  prompt: Help me create a simple iOS app
project_id: oXdhpTezLny4SMMEBTtV
published_at: null
requirements:
- description: Xcode 14 or later
  type: software
- description: macOS Monterey or later
  type: system
- description: Basic Swift knowledge
  type: knowledge
slug: ios-app-development-with-xcode
storage:
  compression_enabled: true
  gcs_path: null
  last_sync: null
  max_file_size_mb: 100
  size_bytes: null
title: iOS App Development with Xcode
tools:
- name: Xcode
  role: IDE
  type: platform
  version: 14+
- name: Swift
  role: Programming Language
  type: language
  version: 5+
updated_at: 2025-03-20 18:50:59.256000
