name: SimpleIOSApp
description: A simple iOS counter application built with Swift and XcodeGen
repository: https://github.com/memextech/ios-template
card_image: https://raw.githubusercontent.com/memextech/ios-template/main/images/ios-card.png
hero_image: https://raw.githubusercontent.com/memextech/ios-template/main/images/ios-hero.png
tags:
  - ios
  - swift
  - mobile
  - xcodegen
  - counter-app